### PR TITLE
Ignore failed descriptor reads on Windows

### LINKED ISSUE #361: Strange and undescribed error thrown once discovering services is called
**Describe the bug**
After connecting and running the following lines, the error thrown is `Error: Other("Error { code: HRESULT(0x8000FFFF), message: \"Catastrophic failure\" }")`

```
let is_connected = peripheral.is_connected().await?;
println!("Now connected ({:?}) to peripheral {:?}...", is_connected, &local_name);
peripheral.discover_services().await?;
println!("Discover peripheral {:?} services...", &local_name);
```

**Actual behavior**
```
Connecting to peripheral "DMRRBA-004"...
Now connected (true) to peripheral "DMRRBA-004"...
Error: Other("Error { code: HRESULT(0x8000FFFF), message: \"Catastrophic failure\" }")
```

### PR DESCRIPTION
**Pull request by DavidZemon**
This brings the Windows implementation in line with Linux

Fixes #361

### CODE REVIEW

**Comment by DavidZemon** [comment]
I tossed a release commit into the branch on the off chance you'd be willing to get this released today, but would be happy to drop/edit that commit if you're not ready to release yet.

**Comment by DavidZemon** [comment]
I've just added another commit in the middle of the branch that adds better low-level handling of the characteristics. After testing my first fix, I found that it was still failing on some devices because `GattCommunicationStatus::AccessDenied` was being treated as a full-blown error.

**Comment by DavidZemon** [comment]
Release commit has been amended with today's date.

**Review by qdot — APPROVED** [review]

**Comment by qdot** [comment]
Ok, I gotta say, submitted the CHANGELOG update and updating it's date in the PR daily is a surprisingly good way to make sure I don't forget about this PR. :P

**Comment by DavidZemon** [comment]
Is the release to crates.io automatic? Just wondering when I should I update my project that is using `btleplug`.

**Comment by DavidZemon** [comment]
> Is the release to crates.io automatic? Just wondering when I should I update my project that is using `btleplug`.

Nevermind - I see this was merged into `dev` not `master`, so obviously not going to release automatically.

**Comment by qdot** [comment]
Nope, releases are done by hand still, but it's published now.

**Comment by DavidZemon** [comment]
> Nope, releases are done by hand still, but it's published now.

Thanks! Already have my PR up to use the new version and it's one of the last things for getting the app deployed to prod, so thank you!

**Pull request merged**
