### PR TITLE
corebluetooth: conditionally link against AppKit framework

### PR DESCRIPTION
**Pull request by jhonboy121**
* this fixes compilation of dylib for ios targets since AppKit is only available in macos sdk

### CODE REVIEW

**Review by qwandor — APPROVED** [review]

**Comment by jhonboy121** [comment]
@qwandor workflow run failed because of rustfmt, merging this will not be an issue

**Comment by qwandor** [comment]
I just realised that this PR was against the wrong branch, it should have been merged into `dev` rather than `master`.

**Comment by jhonboy121** [comment]
Ugh, my bad. Anyways this is a small change and *should* not pose any problems.

**Comment by qdot** [comment]
BTW I rebased dev on master to fix this, required a force push so you'll need to act accordingly on next pull.

**Comment by jhonboy121** [comment]
> I've been getting complaints about this elsewhere so I'll see about doing a point release with this soon anyways.

Yes, linker throws the error only with dylib/cdylib crate-type.

**Comment by micolous** [comment]
> I've been getting complaints about this elsewhere so I'll see about doing a point release with this soon anyways.

I'd be pretty keen to see a release with #290 too, because that issue makes scanning advertisements pretty much unusable on Linux/bluez. I had pinned the commit, but then unfortunately it was broken by the force-push for this.

**Comment by qdot** [comment]
v0.10.5 is now on crates. :3

**Pull request merged**
