### PR TITLE
Added `on_event` example

### PR DESCRIPTION
**Pull request by vietlq**
Added `on_event` example. Related to https://github.com/deviceplug/btleplug/issues/40

My VSCode also removed some trailing spaces, I hope you don't mind.

Please squash upon merging. Thanks.

### CODE REVIEW

**Comment by vietlq** [comment]
@qdot do you want me to make more changes?

**Comment by qdot** [comment]
I'm way behind on PRs right now, I'll try to look this over soon.

**Comment by blandger** [comment]
Where the code  ` = channel(256);` comes from ? What is library is used for that function?

**Comment by qdot** [comment]
That's using async_std channels (and tasks, which is a bad idea since it locks us to a runtime), which came in as part of the corebluetooth changes I made. I need to swap it to use futures::channel at some point soon, I'm just used to async_std and it was the easiest thing to get the library out the door.

**Comment by blandger** [comment]
@qdot Thanks, I figured that out.

But I still can't figure out how to connect to BLE and start receiving data in loop, I would like to have ability to reconnect after link drops and continue receiving data. There is luck of good examples. I'm thinking about possible implementation ways.

I would like create kind of server app. It should keep BL connection with medical device(s), store data locally, interact with user by some UI (web I suppose).
Currently I can't do even easy tasks without examples. So I'm trying to figure out how to create simple code for such stuff.
Thank you for efforts. I would like to help with unit tests. I will keep going to create something by myself.

**Comment by qdot** [comment]
Apologies for taking so long to bring this in. See #45 about the channel() calls too, which will hopefully be removed in v0.5.0 (which at my current pace will happen sometime between next week and the heat death of the sun.)

**Pull request merged**
